### ISSUE TITLE
Try to use USFM on Notepad++

### ISSUE THREAD

**Issue by luisrsn** [DavidHaslam/USFM#3]
Hi brother,

I'm from Brazil and I would like to use the syntax USFM to edit some files on Notepad++ but when I try to import a new language (USFM.xml) appear the message: Fail to import.

Can you help me send the step-by-step to do it correctly?

Best regards

**Comment by DavidHaslam** [comment]
http://docs.notepad-plus-plus.org/index.php/Syntax_Highlighting_Sharing

No further help will be offered. Others have used this successfully.
